apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: require-team-label
policies:
  - policy.yaml
resources:
  - resource.yaml
results:
  - policy: require-team-label
    rule: check-team
    resources:
      - labelled
    kind: Pod
    result: pass
